### ISSUE TITLE
README.md should contain a better description of the goal we are trying to achieve here

### ISSUE THREAD

**Issue by mtuktarov** [yegor256/apex2www#17]
I'm looking at the repo and I don't quite understand the idea:

1. As I understand it, the problem is that when using an SSL connection something redirects (what? Why? Is this a known issue with using something specific?) request to another domain name (subdomain) and the browser doesn't like that the certificate is issued for the apex domain, i.e., one that does not contain www. For example, example.com redirects to www.example.com.
2. If the first point is correct, then it means there is at least a certificate already in place containing apex. What's stopping us from issuing a certificate for multiple domain names?
3. In general, it would be great to describe the scenario.

**Comment by yegor256** [comment]
@mtuktarov looks like a mix of problems. The SSL problem is described here: #6 The lack of documentation is another problem, which I can try to fix in this ticket

**Comment by yegor256** [comment]
@mtuktarov in README, I added a link to redirect.pizza, hope this should help understand what this service is for
